version: "3.8"

services:
  mlflow:
    image: python:3.9
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/mlruns  # Stores MLflow data
    command: mlflow ui --host 0.0.0.0 --port 5000 --backend-store-uri file:///mlruns

  fastapi:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
      - ./mlruns:/mlruns  # Shares MLflow data
    depends_on:
      - mlflow
